default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  timeout: 5000

development:
  <<: *default
  database: smarthome_dev

test:
  <<: *default
  database: smarthome_test

production:
  <<: *default
  database: smarthome_prod
